"""
Export Service — Generate DOCX files from workflow SOPs and knowledge.
"""
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from io import BytesIO

from db import get_db
from models.user import User
from models.workflow import Workflow
from services.auth import get_current_user

router = APIRouter()


@router.get("/workflow/{workflow_id}/docx")
def export_workflow_docx(
    workflow_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Export a workflow SOP to DOCX format."""
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    wf = db.query(Workflow).filter(Workflow.id == workflow_id).first()
    if not wf:
        raise HTTPException(status_code=404, detail="Workflow not found")

    doc = Document()

    # ── Title Page ─────────────────────────────────────────────────────────
    title = doc.add_heading(wf.title, level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run("Standard Operating Procedure")
    run.font.size = Pt(14)
    run.font.color.rgb = RGBColor(0x0E, 0xA5, 0xE9)  # neon-cyan

    # Metadata table
    meta_table = doc.add_table(rows=4, cols=2)
    meta_table.style = "Light Grid Accent 1"
    meta_data = [
        ("Department", wf.department or "N/A"),
        ("Area", wf.area or "N/A"),
        ("Version", str(wf.version or 1)),
        ("Status", "Approved ✓" if wf.is_approved else "Draft"),
    ]
    for i, (label, value) in enumerate(meta_data):
        meta_table.rows[i].cells[0].text = label
        meta_table.rows[i].cells[1].text = value

    doc.add_paragraph()

    # ── Description ────────────────────────────────────────────────────────
    if wf.description:
        doc.add_heading("Deskripsi", level=1)
        doc.add_paragraph(wf.description)

    # ── Steps ──────────────────────────────────────────────────────────────
    if wf.steps:
        doc.add_heading("Langkah-Langkah Proses", level=1)
        for step in wf.steps:
            step_num = step.get("step", "?")
            action = step.get("action", "")
            details = step.get("details", "")
            tools = step.get("tools", "")

            p = doc.add_paragraph()
            run = p.add_run(f"Step {step_num}: ")
            run.bold = True
            run.font.size = Pt(11)
            p.add_run(action)

            if details:
                doc.add_paragraph(f"    Detail: {details}", style="List Bullet")
            if tools:
                doc.add_paragraph(f"    Tools: {tools}", style="List Bullet")

    # ── AI SOP Draft ───────────────────────────────────────────────────────
    if wf.ai_sop_draft:
        doc.add_page_break()
        doc.add_heading("AI-Generated SOP", level=1)
        # Convert markdown-like text to paragraphs
        for line in wf.ai_sop_draft.split("\n"):
            line = line.strip()
            if not line:
                continue
            if line.startswith("# "):
                doc.add_heading(line[2:], level=1)
            elif line.startswith("## "):
                doc.add_heading(line[3:], level=2)
            elif line.startswith("### "):
                doc.add_heading(line[4:], level=3)
            elif line.startswith("- ") or line.startswith("* "):
                doc.add_paragraph(line[2:], style="List Bullet")
            elif line.startswith("1. ") or line.startswith("2. ") or line.startswith("3. "):
                doc.add_paragraph(line[3:], style="List Number")
            else:
                doc.add_paragraph(line)

    # ── Safety Notes ───────────────────────────────────────────────────────
    if wf.ai_safety_notes:
        doc.add_heading("⚠️ Catatan Keselamatan", level=1)
        doc.add_paragraph(wf.ai_safety_notes)

    # ── Optimization Suggestions ───────────────────────────────────────────
    if wf.ai_optimization:
        doc.add_heading("💡 Saran Optimasi", level=1)
        doc.add_paragraph(wf.ai_optimization)

    # ── Estimated Time ─────────────────────────────────────────────────────
    if wf.ai_estimated_time:
        doc.add_heading("⏱️ Estimasi Waktu", level=1)
        doc.add_paragraph(wf.ai_estimated_time)

    # ── Footer ─────────────────────────────────────────────────────────────
    doc.add_page_break()
    footer_p = doc.add_paragraph()
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer_p.add_run("Generated by ShiftMind AI — PT Garuda Yamato Steel")
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    # Save to buffer
    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)

    safe_title = "".join(c if c.isalnum() or c in " _-" else "_" for c in wf.title)[:50]
    filename = f"SOP_{safe_title}_v{wf.version or 1}.docx"

    return StreamingResponse(
        buffer,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'}
    )
